
      
server:  port: 9000

      
spring:  application:    name: demo-producer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/